services:
  android-emulator:
    image: budtmo/docker-android:emulator_14.0
    container_name: android_emulator
    privileged: true
    ports:
      - "6080:6080"   # VNC / Web UI
      - "5554:5554"
      - "5555:5555"
    environment:
      - DEVICE=Samsung Galaxy S10
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
      - EMULATOR_ARGS=-no-audio -no-boot-anim
    devices:
      - /dev/kvm:/dev/kvm
    healthcheck:
      test: ["CMD", "sh", "-c", "adb devices | grep -q device"]
      interval: 15s
      timeout: 10s
      retries: 30
      start_period: 120s

  maui-builder:
    build:
      context: .
      dockerfile: Kommunist.Application/Dockerfile
    container_name: maui_builder
    network_mode: "service:android-emulator"
    depends_on:
      android-emulator:
        condition: service_healthy
    working_dir: /app
    entrypoint: []
    command:
      - /bin/bash
      - -c
      - >
        set -e;
        echo 'Waiting for emulator to fully start...';
        sleep 90;
        echo 'Checking for connected devices...';
        for i in $(seq 1 60); do
          echo "Attempt $$i/60: Listing devices...";
          adb devices -l;
          NUM=$$(adb devices | grep -v "List" | grep -c "device" || echo "0");
          if [ "$$NUM" -gt 0 ]; then
            echo "Device detected!";
            break;
          fi;
          if [ $$i -eq 60 ]; then
            echo "No device found after 60 attempts";
            exit 1;
          fi;
          echo "Waiting... ($$i/60)";
          sleep 10;
        done;
        echo 'Waiting for device to be ready...';
        adb wait-for-device;
        echo 'Waiting for boot to complete...';
        for j in $(seq 1 120); do
          STATUS=$$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r' || echo "0");
          if [ "$$STATUS" = "1" ]; then
            echo "Boot completed!";
            break;
          fi;
          echo "Still booting... ($$j/120)";
          sleep 5;
          if [ $$j -eq 120 ]; then
            echo "Boot timeout after 10 minutes";
            exit 1;
          fi;
        done;
        echo 'Installing APK...';
        APK=$$(ls /app/*.apk 2>/dev/null | head -n 1 || echo "");
        if [ -z "$$APK" ]; then
          echo "No APK file found in /app/";
          ls -la /app/;
          exit 1;
        fi;
        echo "Installing: $$APK";
        if adb install -r "$$APK"; then
          echo 'APK installed successfully!';
        else
          echo 'APK installation failed!';
          exit 1;
        fi;
        echo 'Deployment complete! Container will stay alive...';
        tail -f /dev/null