services:
  android-emulator:
    image: budtmo/docker-android:emulator_14.0
    container_name: android_emulator
    privileged: true
    ports:
      - "6080:6080"   # VNC / Web UI
      - "5554:5554"
      - "5555:5555"
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
      - DEVICE=Samsung Galaxy S10
      - EMULATOR_ARGS=-no-audio -no-boot-anim
    devices:
      - /dev/kvm:/dev/kvm
    healthcheck:
      test: ["CMD", "adb", "devices"]
      interval: 10s
      timeout: 5s
      retries: 10

  maui-builder:
    build:
      context: .
      dockerfile: Kommunist.Application/Dockerfile
    container_name: maui_builder
    depends_on:
      android-emulator:
        condition: service_healthy
    working_dir: /app
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        echo '🕒 Waiting for emulator...'
        sleep 30
        adb connect android-emulator:5555
        adb wait-for-device
        echo '📱 Installing APK...'
        adb install -r /app/*.apk
        echo '✅ APK installed successfully!'
