name: .NET MAUI CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Install workloads depending on OS
    - name: Install workloads
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          dotnet workload install maui-android --skip-manifest-update
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          dotnet workload install maui-android maui-ios maui-maccatalyst --skip-manifest-update
        elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          dotnet workload install maui-android maui-windows --skip-manifest-update
        fi

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
